# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pGdNh40CfHy_L0UJqrW-Rq42u3POe_6j
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import (train_test_split, KFold , StratifiedKFold, 
                                     cross_val_score, GridSearchCV, 
                                     learning_curve, validation_curve)

df=pd.read_csv("glass.csv")
df.head()
features = df.columns[:-1].tolist()

df.info()

df.describe()

for feat in features:
    skew = df[feat].skew()
    sns.distplot(df[feat], kde= False, label='Skew = %.3f' %(skew), bins=30)
    plt.legend(loc='best')
    plt.show()

scaler=StandardScaler()
scaled_feature=scaler.fit_transform(df.drop(columns=["Type"]))
scaled=pd.DataFrame(scaled_feature,columns=df.columns[:-1])

X_train,X_test,y_train,y_test=train_test_split(scaled,df['Type'],test_size=.3)

Knn_euclidean=KNeighborsClassifier(n_neighbors=5,metric='euclidean')
Knn_euclidean.fit(X_train,y_train)

y_pred_euclidean=Knn_euclidean.predict(X_test)

Knn_manhattan=KNeighborsClassifier(n_neighbors=5,metric='manhattan')
Knn_manhattan.fit(X_train,y_train)

y_pred_manhattan=Knn_manhattan.predict(X_test)

acc = accuracy_score(y_test, y_pred_euclidean)
acc

ac2=accuracy_score(y_test, y_pred_manhattan)
ac2